# Generated by Django 4.1.2 on 2024-07-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genero_rename_nompreproducto_producto_nombreproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_product',
            field=models.AutoField(db_column='idProducto', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
