# Generated by Django 4.1.2 on 2024-07-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_producto_id_producto_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_cat',
            field=models.AutoField(db_column='idCategoria', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
